camera0: "30958851"
camera1: "30957651"
frame_width: 512
frame_height: 512
mono_calibration_frames: 100
stereo_calibration_frames: 100
view_resize: 1
checkerboard_box_size_scale : 45
checkerboard_rows: 4
checkerboard_columns: 3
cooldown: 50
